### ISSUE TITLE
Split file.copy method to local and remote copy methods

### ISSUE THREAD

**Issue by homm** [uploadcare/pyuploadcare#119]
We should create two separate copy methods. Unfortunately, we have confusing API on REST side, but we don't have to copy them as is. In fact, we have two copy operations: copy to UC storage and copy to some target. For the local copy we need `effects` and `store` arguments, for the remote copy we need `effects `, `make_public`, `pattern`.

**Comment by khazamov** [comment]
I agree that methods should be split, but I still think that kwargs should be used. Remote copy will grow in the number of parameters even further when the support for new storage types are added. 

>>> kwargs makes spelling errors possible and also breaks compatibility.
Tests should indicate compatibility break.
