### ISSUE TITLE
Update Widget to Version 3

### ISSUE THREAD

**Issue by MicahLyle** [uploadcare/pyuploadcare#130]
Is it possible to update the widget now to the latest version (I.E. version 3.1.1 as of the time of writing)?

**Comment by dmitry-mukhin** [comment]
sure,
but you may use the latest widget even now, via config setting.

**Comment by MicahLyle** [comment]
Ah thanks you had it right here: https://pyuploadcare.readthedocs.io/en/latest/django-widget.html#settings

**Comment by dmitry-mukhin** [comment]
bumped widget to 3.2.3 in lib version 2.3.1
