### ISSUE TITLE
Break with Django2.0 Update

### ISSUE THREAD

**Issue by jamesshaw49** [uploadcare/pyuploadcare#131]
Hi,

I thought I would let you guys know that your python-django library breaks with the Django 2.0 update. The error:

AttributeError: 'ImageField' object has no attribute ‘_get_val_from_obj'

This happens when the ImageField is serialised through djangorest.

 ‘_get_val_from_obj' is depreciated and removed In Django2.0.

James

**Comment by dmitry-mukhin** [comment]
Thanks,

we'll look into it (or you can beat us to the punch with your own PR:)

**Comment by dmitry-mukhin** [comment]
fixed in version 2.3.1
