### ISSUE TITLE
getting links with image extensions

### ISSUE THREAD

**Issue by Six-wars** [uploadcare/pyuploadcare#147]
So far I've been using this without an issue but so far working on my twitter card integration which needs an image url and this app returns an image without the extension like .jpg I wonder if twitter isn't taking the link as a valid image url.
If so then it would be advantageous to be able to add this extension even if the backend simply understands what it's for an ignores it.

**Comment by dmitry-mukhin** [comment]
you can get filename from file info and add anything to your URL.
simply adding "image.jpeg" should also work :)

**Comment by Six-wars** [comment]
I'm curious how I'd do that, I'm using this with django and one example of
a url from the model is
https://ucarecdn.com/5d00c96b-126b-4516-8192-8cec330b6b5a/-/crop/646x646/462,0/-/resize/200x200/

**Comment by sharov** [comment]
@Six-wars just add "image.jpeg" to end of this URL
https://ucarecdn.com/5d00c96b-126b-4516-8192-8cec330b6b5a/-/crop/646x646/462,0/-/resize/200x200/image.jpg
