### ISSUE TITLE
Batch delete/store methods should work for arbitrary list sizes.

### ISSUE THREAD

**Issue by dmitry-mukhin** [uploadcare/pyuploadcare#199]
### Brief description of the feature and motivation behind it

Motivated by #196

Currently, if user wants to remove or store more than 100 files, they have to generate chunks of 100 files in their code.
This can and should be safely implemented in the client/api methods.

**Comment by evgkirov** [comment]
This already has been implemented in https://github.com/uploadcare/pyuploadcare/pull/227/files for both the `store_files` and `delete_files` methods.
