### ISSUE TITLE
Enable adding metadata to uploads

### ISSUE THREAD

**Issue by jensenbox** [uploadcare/pyuploadcare#200]
It appears that there is the ability to send metadata information using the API but the code found here does not allow for its addition: https://github.com/uploadcare/pyuploadcare/blob/main/pyuploadcare/api/api.py#L207

https://uploadcare.com/api-refs/upload-api/#operation/baseUpload

Would you be able to add this or would you prefer a PR?

**Comment by dmitry-mukhin** [comment]
PRs are always welcome :)

**Comment by rsedykh** [comment]
Hi @jensenbox. Please check out the new library version — https://github.com/uploadcare/pyuploadcare/releases/tag/v4.0.0.
