### ISSUE TITLE
multipage conversion (save_in_group param in documentJobSubmitParameters)

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/pyuploadcare#258]
https://uploadcare.com/docs/transformations/document-conversion/#multipage-conversion

**Comment by evgkirov** [comment]
From the [docs](https://uploadcare.com/docs/transformations/document-conversion/):

> Note: The API response to the conversion request doesn't indicate the group UUID since the group identifier includes the number of files in the group, which is determined later.
> 
> To get the UUID of the converted files group:
> 
>     curl -X GET \
>         -H "Content-Type: application/json" \
>         -H "Accept: application/vnd.uploadcare-v0.7+json" \
>         -H "Authorization: Uploadcare.Simple $YOUR_PUBLIC_KEY:$YOUR_SECRET_KEY" \
>         "https://api.uploadcare.com/convert/document/:UUID/"

`GET /convert/document/:UUID/` is missing from the [API ref](https://uploadcare.com/api-refs/rest-api/v0.7.0/#tag/Conversion/operation/documentConvert)
