### ISSUE TITLE
Update webhooks API (event types and versioning)

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/pyuploadcare#259]
New event types. Current enum:
* file.uploaded
* file.infected (it will be deprecated in favor of info_upldated in the future updates)
* file.stored
* file.deleted
* file.info_updated

https://uploadcare.com/docs/webhooks/#event-types

<img width="593" alt="image" src="https://github.com/uploadcare/uploadcare-php/assets/515987/347f7835-497c-42e9-8c16-65f5ea69b96c">

Also, please check the versioning. It's easier to just send current API version, because from within API 0.7 you can't create 0.6 anyways (but you'll be able to create 0.8 when they it is released).

<img width="386" alt="image" src="https://github.com/uploadcare/uploadcare-php/assets/515987/eaac3942-6cd3-41e9-9135-ae7764a5428c">

Payload is also updated (new `initiator` field), but since it's not part of the library, nothing is to update here.

p.s. Don't forget to update uploadcare-php-example if necessary.

**Comment by evgkirov** [comment]
Added a type hint there for better validation and nice IDE/LSP completions.

Haven't checked **pyuploadcare**-example yet.

PR #269

**Comment by evgkirov** [comment]
Merged.

`version` field is ok.
