### ISSUE TITLE
Deprecate PUT /group/{uuid}/storage/

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/pyuploadcare#261]
It was deprecated.

<img width="868" alt="image" src="https://github.com/uploadcare/uploadcare-php/assets/515987/56a7534d-8b27-42c9-81a7-af10a92315f4">

https://uploadcare.com/api-refs/upload-api/#tag/Groups/operation/filesGroupInfo
https://uploadcare.com/api-refs/rest-api/v0.7.0/#tag/Group/operation/groupInfo

To store or remove files from a group, query the list of files in it, split the list into chunks of 100 files per chunk and then perform batch file storing or batch file removal for all the chunks.

p.s. Don't forget to update uploadcare-php-example if necessary.

**Comment by rsedykh** [comment]
@evgkirov I see it's done. Are there anything to change in uploadcare-php-example?

**Comment by evgkirov** [comment]
Depends on how you call it.

1. `FileGroup.store` helper method iterates over files.
2. However, `GroupsAPI.store` exists and it does request `PUT /group/{uuid}/storage/`.

I will put a deprecation warning in `GroupsAPI.store`. I'll also add a deprecation warning for calls to `FileGroup.datetime_stored`.

Question: is `PUT /group/{uuid}/storage/` deprecated to the extent that it has been completely removed from [the API documentation](https://uploadcare.com/api-refs/rest-api/v0.7.0/#tag/Group)?

**Comment by evgkirov** [comment]
Is there an API changelog that is publicly available?

https://uploadcare.com/docs/changelog/ doesn't seem to have any information about these changes (deprecation of `PUT /group/{uuid}/storage/` and `datetime.stored`)

**Comment by rsedykh** [comment]
https://uploadcare.com/api-refs/rest-api/v0.7.0/#tag/Changelog

But it's not sorted by the date. It will be updated fairly soon: first batch of 0.7.0 updates, and than "0.7.x" updates will be sorted by the date.

cc @KamillaGarifullina

**Comment by rsedykh** [comment]
To answer your question: it will be removed in the next version of the API. Right now it is marked as deprecated, but it continue to work for now.

**Comment by evgkirov** [comment]
`datetime_storage` exists in Upload API and marked with _Deprecated_.

No mention of `datetime_storage` in REST API doc. Does this field exist in API 0.7.0?

**Comment by rsedykh** [comment]
It should (because deprecation happened waaay later than the release of REST 0.7). Can you check if it's there?

**Comment by evgkirov** [comment]
I can.

But if it does exist, why the mention of it was removed from the REST API spec instead of being marked as deprecated?

**Comment by evgkirov** [comment]
`datetime_storage` doesn't exist in `GET /groups/:uuid/ in v0.7.0

`PUT /group/:uuid/storage/` doesn't exist in v0.7.0

pyuploadcare, however, allows for use of older API versions (`uc = Uploadcare(..., api_version="0.6")`). So I'm not deleting these methods from the library, as some folks might use the newer versions of the library with older API versions. Added deprecation warnings.
