### ISSUE TITLE
Allow to pass a UUID + params when generating signed URL (ACL)

### ISSUE THREAD

**Issue by optlsnd** [uploadcare/pyuploadcare#264]
### Brief description of the feature and motivation behind it

Currently, the `AkamaiSecureUrlBuilder` class allows for signing a whole URL. In some cases, there's a need to generate a universal ACL token with wildcards. For example, we can specify an ACL as follows:

`/{uuid}/*`

and the token generated will be applicable to any variation of the file associated with the `{uuid}`. E.g., `https://ucarecdn.com/{uuid}/-/resize/360x/-/format/auto/`

See https://github.com/akamai/EdgeAuth-Token-Python/blob/master/akamai/edgeauth/edgeauth.py#L183 for reference.

**Comment by evgkirov** [comment]
merged
