### ISSUE TITLE
How can I migrate from normal ImageField?

### ISSUE THREAD

**Issue by saulshanabrook** [uploadcare/pyuploadcare#70]
I have a Django site currently running that hosts all of it's assets on S3, through `django-storages`. What is the migration pack look like to change over all my assets to use UploadCare?

**Comment by dmitry-mukhin** [comment]
There's a tool that can help with migration automation: https://github.com/uploadcare/migro
As for Django specific migration, I'd suggest to make three step migration for this:

1. schema migration that adds new field handled by `pyuploadcare`
2. data migration that uploads files handled by Django's original `FileField` to `pyuploadcare.dj.models.FileField`. Optionally, remove files from S3 here or in separate data migration.
3. schema migration that removes Django's `FileField` field.
